### ISSUE TITLE
items become not supported

### ISSUE THREAD

**Issue by starlessboi** [lxndrp/pdh2zabbix#2]
Hi
I created a template using your script for IIS perf counters, but after adding template and adding filters, items become not supported with error: Unsupported item key.
did I missed some steps?
is there any instruction for using your script to monitor IIS perf counters?

**Comment by lxndrp** [comment]
Hi @starlessboi ,

there are no specific instructions for IIS; they work the same as all other performance counters. To help you out, I need a number of details regarding your request:
- How did you call the script (exact command line)?
- On which version of Windows did you run the template generation (exact version)?
- On which version of Windows did you query the values (exact version)?

Also, it would be helpful if you could try to query a few of the counters manually, using the corresponding Windows tools on the command line.

Regards,
Alexander

**Comment by starlessboi** [comment]
Hi
Thanks
That was my fault in regard to user parameter, I succeed finally.
thanks for your great script
