### ISSUE TITLE
Problem with keys more than one word

### ISSUE THREAD

**Issue by mbuyukkarakas** [lxndrp/pdh2zabbix#3]
It's not possible to create template items from countersets which contains space character or some special characters like (

DFS Namespaces, DFS Replicated Folders, DFS Replication Connections ,Network Adapter , Network Interface, Directory Services(NTDS)

How can we fix this ?

Thank you.
Mehmet

**Comment by lxndrp** [comment]
Just make sure that the call argument for the name is quoted properly, especially in your UserParameter. Then, it should work.
